"""New

Revision ID: 5a562bee01ff
Revises: e9ebd172dcf3
Create Date: 2022-10-02 12:10:52.540241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a562bee01ff'
down_revision = 'e9ebd172dcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
