"""New 3

Revision ID: e40dd3e61c63
Revises: 5a562bee01ff
Create Date: 2022-10-02 12:35:58.055426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40dd3e61c63'
down_revision = '5a562bee01ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
